# 로그인
POST localhost:8080/api/v1/user/login

###
# 로그인
GET localhost:8080/api/v1/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNzA4MTgyMTk1fQ.CCsJM9TbFiyCeB2sZDdXC-g3gpjU57y1mu8xr_pNNTI

###
# 정보 수정 (by 영인)
POST localhost:8080/api/v1/user/basicInformation
Content-Type: application/json

{
  "name": "지혁",
  "birthDay": "2024-02-16 00:00",
  "gender": "MALE",
  "mbti": "ENTJ",
  "major": "컴퓨터공학부"
}

###
# 이미지 업로드
POST localhost:8080/api/v1/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzA4MTczNzAyfQ.2YshDjkNM-ccVpTCdgTOBcGQjob51OJPLTphtN2ezYk

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="timetable.jpg"

< ./timetable.jpg
--WebAppBoundary--
Content-Disposition: form-data; name="files"; filename="cat2.jpg"

< ./cat.jpg
--WebAppBoundary--

###
# 내가 현재 QR을 만들었는가?
GET localhost:8080/api/v1/meet/request/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzA4MTc4MDcxfQ.VKSQtPmZpr-s0XuGwfqWz7cPZg3QgHoDsuDmqtc26cQ

###
# 1. 없음 -> QR 생성
POST localhost:8080/api/v1/meet/request
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzA4MTc4MDcxfQ.VKSQtPmZpr-s0XuGwfqWz7cPZg3QgHoDsuDmqtc26cQ

#### QR 만드는 API => 클라에 띄우고
POST localhost:8080/api/v1/meet/make-qr?meetUpId=4a16333d-b218-4d9c-a414-0eb4827ab3ce::2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzA4MTc4MDcxfQ.VKSQtPmZpr-s0XuGwfqWz7cPZg3QgHoDsuDmqtc26cQ

###
# 2. 있음 -> meetUpId 를 받을 수 있음
POST localhost:8080/api/v1/meet/request
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzA4MTc4MDcxfQ.VKSQtPmZpr-s0XuGwfqWz7cPZg3QgHoDsuDmqtc26cQ

###
# QR 이 생기고 나면
# UserA : meetUpId 를 가지고 누군가 들어왔는지 계속 체크 -> 들어왔으면 채팅방 입장
# UserB : QR 을 찍어서 -> meetUpId 를 받아서 -> 채팅방 입장

###
# stream 으로 결과를 받는 flow