openai:
  api-key: YOUR_API_KEY
  model: gpt-3.5-turbo # or gpt-4-0125-preview

weaviate:
    host: YOUR_HOST
    api-key: YOUR_API_KEY
    scheme: YOUR_SCHEMA


spring:
  jpa:
    defer-datasource-initialization: true # 개발용
#  datasource:
#    url: r2dbc:h2:mem:///test;DATABASE_TO_UPPER=FALSE
#    driver-class-name: org.h2.Driver
